<?php
declare(strict_types=1);
/**
 * @var Magento\Framework\View\Element\Template $block
 * @var STLK\Career\ViewModel\Application\FormViewModel $formViewModel
 * @var Magento\Framework\Escaper $escaper
 */
$formViewModel = $block->getData('form_view_model');
?>

<?php if ($formViewModel->checkIfFormSubmittedWithSuccess()): ?>
    <div class="career-application-form-success">
        <h2><?= $escaper->escapeHtml(__('The form has been sent successfully.')); ?></h2>
    </div>
<?php else: ?>
    <div class="career-application-form-fail">
        <h2><?= $escaper->escapeHtml(__('Something went wrong contact with customer service office.')); ?></h2>
    </div>
<?php endif; ?>
<div class="career-application-form">
    <form
        class="application form"
        action="<?= $escaper->escapeHtml($block->getUrl('career/application/submit')); ?>"
        id="application-form"
        method="post">
        <h3><?= $escaper->escapeHtml(__('Application form')); ?></h3>
        <div class="field name required">
            <label class="label" for="name"><span><?= $escaper->escapeHtml(__('Name')); ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?= $escaper->escapeHtml(__('Name')); ?>" class="input-text"
                       type="text"
                       data-validate="{required:true}">
            </div>
        </div>
        <div class="field surname required">
            <label class="label" for="surname"><span><?= $escaper->escapeHtml(__('Surname')); ?></span></label>
            <div class="control">
                <input name="surname" id="surname" title="<?= $escaper->escapeHtml(__('Surname')); ?>"
                       class="input-text" type="text"
                       data-validate="{required:true}">
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $escaper->escapeHtml(__('Email address')); ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?= $escaper->escapeHtml(__('Email address')); ?>"
                       class="input-text" type="text"
                       data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="field positions">
            <label class="label" for="surname"><span><?= $escaper->escapeHtml(__('Position')); ?></span></label>
            <select name="position" id="position" data-validate="{required:true}">
                <?php foreach ($formViewModel->getOpenPositions() as $openPosition): ?>
                    <option
                        value="<?= $escaper->escapeHtml($formViewModel->changeSpacesToUnderscoreForDivValue($openPosition)); ?>">
                        <?= $escaper->escapeHtml($openPosition); ?>
                    </option>;
                <?php endforeach; ?>
            </select>
        </div>
        <div class=" field message required
                ">
            <label class="label" for="message"><span><?= $escaper->escapeHtml(__('Message')); ?></span></label>
            <div class="control">
                <input name="message" id="message" title="<?= $escaper->escapeHtml(__('Message')); ?>"
                       class="input-text" type="text"
                       data-validate="{required:true}">
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary" style="margin-top:7px;">
                <button type="submit" class="action submit primary" title="Save">
                    <span><?= $escaper->escapeHtml(__('Submit')); ?></span>
                </button>
            </div>
        </div>
    </form>
</div>

<script type="text/x-magento-init">
    {
        "#application-form": {
            "validation": {}
        }
    }
</script>
